spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      health-check:
        enabled: true

eureka:
  fetch-registry: true
  register-with-eureka: true
  instance:
    prefer-ip-address: true

