spring:
  main:
    allow-bean-definition-overriding: true
    
  datasource:
    url: jdbc:mysql://localhost:3306/cartechpay-microservice?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
        ddl-auto: update
        
  cloud:
    loadbalancer:
      health-check:
        enabled: true

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
  fetch-registry: true
  register-with-eureka: true
  instance:
    prefer-ip-address: true
